#!/usr/bin/env python3
"""Generate platform entries from the root skill; --check never writes files."""
import argparse
from pathlib import Path


def outputs(root):
    source = (root / 'SKILL.md').read_text(encoding='utf-8')
    if not source.startswith('---\n'):
        raise ValueError('SKILL.md must begin with YAML frontmatter')
    front, body = source[4:].split('\n---\n', 1)
    description = next(line.partition(':')[2].strip() for line in front.splitlines() if line.startswith('description:'))
    marker = '<!-- Generated by scripts/sync_entries.py; edit root SKILL.md or references/, then regenerate. -->\n'
    result = {
        Path('.opencode/skills/zs-teach-skill/SKILL.md'): '---\n' + front + '\n---\n\n' + marker + body.lstrip('\n'),
        Path('.cursor/rules/zs-teach-skill.mdc'): '---\ndescription: ' + description + '\nglobs: *\nalwaysApply: true\n---\n\n' + marker + body.lstrip('\n').replace('](references/', '](../../references/'),
        Path('.github/copilot-instructions.md'): marker + body.lstrip('\n').replace('](references/', '](../references/'),
    }
    for ref in sorted((root / 'references').rglob('*.md')):
        result[Path('.opencode/skills/zs-teach-skill/references') / ref.relative_to(root / 'references')] = ref.read_text(encoding='utf-8')
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--check', action='store_true', help='Report missing or changed generated files without modifying them')
    args = parser.parse_args()
    try:
        expected = outputs(args.root)
    except (OSError, ValueError, StopIteration) as error:
        parser.error(str(error))
    changed = []
    for relative, content in expected.items():
        destination = args.root / relative
        if not destination.exists() or destination.read_bytes() != content.encode('utf-8'):
            changed.append(relative)
            if not args.check:
                destination.parent.mkdir(parents=True, exist_ok=True)
                destination.write_bytes(content.encode('utf-8'))
    # This directory contains generated Markdown only; source removals must propagate.
    bundle_refs = args.root / '.opencode/skills/zs-teach-skill/references'
    stale = [path for path in bundle_refs.rglob('*.md') if path.relative_to(args.root) not in expected]
    for path in stale:
        print(('Stale generated file: ' if args.check else 'Removed generated file: ') + str(path.relative_to(args.root)))
        if not args.check:
            path.unlink()
    for relative in changed:
        print(('Out of sync: ' if args.check else 'Updated: ') + str(relative))
    return int(args.check and bool(changed or stale))


if __name__ == '__main__':
    raise SystemExit(main())
